[[redirects]]
  from = "/"
  to = "https://www.denniscodes.com/"
  status = 200
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "/about"
  to = "https://www.denniscodes.com/about"
  status = 200
  force = true
  query = {path = ":path"}

  [[redirects]]
  from = "/projects"
  to = "https://www.denniscodes.com/projects
  status = 200
  force = true
  query = {path = ":path"}









