[[redirects]]
    from = "/"
    to = "https://www.denmercs.com/"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/pricing"
    to = "https://www.denmercs.com/pricing"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/portfolio"
    to = "https://www.denmercs.com/pricing/portfolio"
    status = 200
    force = true
    headers = {X-From = "Netlify"}
